# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 21:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('dimension', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('vertexCount', models.IntegerField(blank=True)),
                ('faceCount', models.IntegerField(blank=True)),
                ('equation', models.TextField(blank=True)),
                ('boundingBox', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
            ],
        ),
    ]
